name: Build

on: [pull_request, push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install deps - npm
        run: yarn install --frozen-lockfile

      - name: install deps - python
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: typecheck app
        run: yarn tsc --noEmit

      - name: check with prettier
        run: yarn prettier . --check

      - name: check with black
        run: black --check .
